# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/mkdocs/mkdocs.yml
# See: https://www.mkdocs.org/user-guide/configuration/
site_name: Arduino Lint
site_description: Tool to check for problems with Arduino projects
site_url: https://arduino.github.io/arduino-lint/

repo_name: arduino/arduino-lint
repo_url: https://github.com/arduino/arduino-lint
edit_uri: blob/main/docs/

copyright: Copyright 2020 ARDUINO SA (http://www.arduino.cc/)

theme:
  name: material
  logo: img/icon_mac_light.png
  palette:
    primary: teal
    accent: orange

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 4
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.twemoji
  - pymdownx.magiclink:
      repo: arduino-lint
      repo_url_shorthand: true
      user: arduino
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - installation.md
  - Command reference: commands/arduino-lint.md
  - Rules:
      - Introduction: rules.md
      - Sketch: rules/sketch.md
      - Library: rules/library.md
      - Platform: rules/platform.md
      - Package index: rules/package-index.md
  - CONTRIBUTING.md

extra:
  version:
    provider: mike
