[tool.poetry]
name = "arduino-check"
version = "0.0.0"
description = "arduino-check"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
codespell = ">=1.17.1"
