[tool.poetry]
name = "arduino-lint"
version = "0.0.0"
description = "arduino-lint"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

# Integration tests dependencies.
invoke = "^1.7.1"
pytest = "^7.1.3"
python-dateutil = "^2.8.2"
semver = "^2.13.0"

# Documentation generation dependencies.
gitpython = "^3.1.27"
mdx_truly_sane_lists = "^1.3"
mike = "^1.1.2"
mkdocs = "^1.3.1"
mkdocs-material = "^8.5.1"

[tool.poetry.dev-dependencies]
black = "^22.8"
codespell = "^2.2.1"
flake8 = "^5.0.4"
pep8-naming = "^0.13.2"

[tool.black]
line-length = 120
target-version = ["py38"]
