[tool.poetry]
name = "arduino-lint"
version = "0.0.0"
description = "arduino-lint"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

# Integration tests dependencies.
invoke = "^2.1.1"
pytest = "^7.3.1"
python-dateutil = "^2.8.2"
semver = "^3.0.0"

# Documentation generation dependencies.
gitpython = "^3.1.31"
mdx_truly_sane_lists = "^1.3"
mike = "^1.1.2"
mkdocs = "^1.4.3"
mkdocs-material = "^9.1.9"

[tool.poetry.dev-dependencies]
black = "^23.3"
codespell = "^2.2.4"
flake8 = "^6.0.0"
pep8-naming = "^0.13.3"

[tool.black]
line-length = 120
target-version = ["py38"]
