name: Check License

env:
  EXPECTED_LICENSE_FILENAME: LICENSE.txt
  # SPDX identifier: https://spdx.org/licenses/
  EXPECTED_LICENSE_TYPE: GPL-3.0

on:
  push:
    paths:
      - ".github/workflows/check-license.ya?ml"
      # Recognized license files. See: https://github.com/licensee/licensee/blob/master/docs/what-we-look-at.md#detecting-the-license-file
      - "COPYING*"
      - "LICENCE*"
      - "LICENSE*"
  pull_request:
    paths:
      - ".github/workflows/check-license.ya?ml"
      - "COPYING*"
      - "LICENCE*"
      - "LICENSE*"

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby # Install latest version

      - name: Install licensee
        run: gem install licensee

      # See: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository
      - name: Check license file
        run: |
          # See: https://github.com/licensee/licensee
          LICENSEE_OUTPUT="$(licensee detect --json --confidence=100)"

          DETECTED_LICENSE_FILE="$(echo "$LICENSEE_OUTPUT" | jq .matched_files[0].filename | tr --delete '\r')"
          echo "Detected license file: $DETECTED_LICENSE_FILE"
          if [ "$DETECTED_LICENSE_FILE" != "\"${EXPECTED_LICENSE_FILENAME}\"" ]; then
            echo "ERROR: detected license file doesn't match expected: $EXPECTED_LICENSE_FILENAME"
            exit 1
          fi

          DETECTED_LICENSE_TYPE="$(echo "$LICENSEE_OUTPUT" | jq .matched_files[0].matched_license | tr --delete '\r')"
          echo "Detected license type: $DETECTED_LICENSE_TYPE"
          if [ "$DETECTED_LICENSE_TYPE" != "\"${EXPECTED_LICENSE_TYPE}\"" ]; then
            echo "ERROR: detected license type doesn't match expected $EXPECTED_LICENSE_TYPE"
            exit 1
          fi
