name: Check Code Generation

env:
  # See: https://github.com/actions/setup-go/tree/v2#readme
  GO_VERSION: "1.16"

on:
  push:
    paths:
      - ".github/workflows/check-code-generation-task.ya?ml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**.go"
      - "etc/schemas/**/*.json"
  pull_request:
    paths:
      - ".github/workflows/check-code-generation-task.ya?ml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**.go"
      - "etc/schemas/**/*.json"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Generate code
        run: task go:generate

      - name: Check for forgotten code generation
        run: git diff --color --exit-code
