name: Check Python

env:
  # See: https://github.com/actions/setup-python/tree/v2#available-versions-of-python
  PYTHON_VERSION: "3.8"

on:
  push:
    paths:
      - ".github/workflows/check-python-task.ya?ml"
      - "**.py"
      - ".flake8"
      - "pyproject.toml"
      - "Taskfile.yml"
  pull_request:
    paths:
      - ".github/workflows/check-python-task.ya?ml"
      - "**.py"
      - ".flake8"
      - "pyproject.toml"
      - "Taskfile.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: pip install poetry

      - name: Lint Python files
        run: task python:check
