name: Check formatting

on:
  push:
    paths:
      - ".github/workflows/check-formatting.yml"
      - "Taskfile.yml"
      - ".prettierrc"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"
  pull_request:
    paths:
      - ".github/workflows/check-formatting.yml"
      - "Taskfile.yml"
      - ".prettierrc"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Format documentation
        run: task docs:format

      - name: Check documentation formatting
        run: git diff --color --exit-code

      - name: Format configuration files
        run: task config:format

      - name: Check configuration file formatting
        run: git diff --color --exit-code
