name: Lint shell scripts

on:
  push:
    paths:
      - ".github/workflows/lint-shell.yml"
      - "**.sh"
  pull_request:
    paths:
      - ".github/workflows/lint-shell.yml"
      - "**.sh"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Taskfile
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Lint shell scripts
        run: task shell:lint
