name: Check Workflows

on:
  push:
    paths:
      - ".github/workflows/lint-config.yml"
      - ".github/workflows/*.ya?ml"
      - "Taskfile.ya?ml"
  pull_request:
    paths:
      - ".github/workflows/lint-config.yml"
      - ".github/workflows/*.ya?ml"
      - "Taskfile.ya?ml"
  schedule:
    # Run every Tuesday at 03:00 UTC to catch breakage caused by changes to the GitHub Actions workflow schema
    - cron: "0 3 * * 2"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Lint configuration files
        run: task --silent ci:validate

