name: Lint code

env:
  # See: https://github.com/actions/setup-go/tree/v2#readme
  GO_VERSION: "1.14"

on:
  push:
    paths:
      - ".github/workflows/lint-code.yml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**/*.go"
  pull_request:
    paths:
      - ".github/workflows/lint-code.yml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**/*.go"

jobs:
  check-errors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Check for errors
        run: task go:vet

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Install golint
        run: |
          go get golang.org/x/lint/golint

      - name: Lint Go code
        run: task --silent go:lint
