name: Test Integration

on:
  push:
    paths:
      - ".github/workflows/test-go-integration-task.ya?ml"
      - "Taskfile.ya?ml"
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "poetry.lock"
      - "pyproject.toml"
      - "tests/**"
  pull_request:
    paths:
      - ".github/workflows/test-go-integration-task.ya?ml"
      - "Taskfile.ya?ml"
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "poetry.lock"
      - "pyproject.toml"
      - "tests/**"

jobs:
  test-go:
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: pip install poetry

      - name: Run integration tests
        run: task go:test-integration
