name: Run tests

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - "**/testdata/**"
      - "etc/schemas/**/*.json"
      - "pyproject.toml"
      - "test/**"
      - "Taskfile.yml"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - "**/testdata/**"
      - "etc/schemas/**/*.json"
      - "pyproject.toml"
      - "test/**"
      - "Taskfile.yml"

jobs:
  test-go:
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Install Taskfile
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Generate code
        run: task go:generate

      - name: Check for forgotten code generation
        run: git diff --color --exit-code

      - name: Build
        run: task build

      - name: Run unit tests
        run: task go:test-unit

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Poetry
        run: pip install poetry

      - name: Run integration tests
        run: task test-integration
