# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/test-go-task.md
name: Run tests

env:
  # See: https://github.com/actions/setup-go/tree/v2#readme
  GO_VERSION: "1.16"

on:
  push:
    paths:
      - ".github/workflows/test-go-task.ya?ml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - "**/testdata/**"
  pull_request:
    paths:
      - ".github/workflows/test-go-task.ya?ml"
      - "Taskfile.yml"
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - "**/testdata/**"

jobs:
  test-go:
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Run unit tests
        run: task go:test

      - name: Send unit tests coverage to Codecov
        if: matrix.operating-system == 'ubuntu-latest'
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage_unit.txt
          flags: unit
          fail_ci_if_error: true
